name: build
on:
  push:
    branches: [ master ]
    tags: [ "*.*.*" ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: install
        run: mvn --settings .github/workflows/mvnsettings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
      - name: deploy
        run: .github/workflows/deploy.sh
